version: '3'

services:
  broker-service:
    image: rwatana/broker-service:1.0.0
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: rwatana/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
  
  authentication-service:
    image: rwatana/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
     DSN: "host=postgres port=5432 user=ryoma password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  

  logger-service:
    image: rwatana/logger-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
  
  mailer-service:
    image: rwatana/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: john.smith@example.com

  postgres:
    image: 'postgres:15.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ryoma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  

  mongo:
    image: 'mongo:4.2.17-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8025:8025"
    deploy:
      mode: global
      
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    deploy:
      mode: global



  

